[project]
name = 'accrue-btc'
description = 'AccrueBTC - non-custodial sBTC yield vault on Stacks'
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'
[contracts.accrue-sats]
path = 'contracts/accrue-sats.clar'
clarity_version = 4
epoch = 'latest'

#[contracts.accrue-vault]
#path = 'contracts/accrue-vault.clar'
#clarity_version = 4
#epoch = 'latest'

#[contracts.vault-token]
#path = 'contracts/vault-token.clar'
#clarity_version = 4
#epoch = 'latest'

#[contracts.vault-trait]
#path = 'contracts/vault-trait.clar'
#clarity_version = 4
#epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = true

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
